export const courses = [
    {
        id: 1,
        lenguage: "Inglés",
        company_course: "juan",
        level: "Principiante",
        instructor: "John Smith",
        schedule: "Lunes y Miércoles, 18:00 - 20:00",
        location: "Centro de Idiomas ABC",
        image: "https://www.civitatis.com/blog/wp-content/uploads/2023/03/shutterstock_1585685068-1920x1280.jpg",
        duration: "1 Month",
    },
    {
        id: 2,
        lenguage: "Portuguese",
        company_course: "tr",
        level: "Principiante",
        instructor: "John Smith",
        schedule: "Lunes y Miércoles, 18:00 - 20:00",
        location: "Centro de Idiomas ABC",
        image: "https://www.civitatis.com/blog/wp-content/uploads/2023/03/shutterstock_1585685068-1920x1280.jpg",
        duration: "1 Month",
    },
    {
        id: 3,
        lenguage: "Italiano",
        company_course: "juan",
        level: "Principiante",
        instructor: "John Smith",
        schedule: "Lunes y Miércoles, 18:00 - 20:00",
        location: "Centro de Idiomas ABC",
        image: "https://www.civitatis.com/blog/wp-content/uploads/2023/03/shutterstock_1585685068-1920x1280.jpg",
        duration: "1 Month",
    },
    {
        id: 4,
        lenguage: "Francés",
        company_course: "juan",
        level: "Principiante",
        instructor: "John Smith",
        schedule: "Lunes y Miércoles, 18:00 - 20:00",
        location: "Centro de Idiomas ABC",
        image: "https://www.civitatis.com/blog/wp-content/uploads/2023/03/shutterstock_1585685068-1920x1280.jpg",
        duration: "1 Month",
    },
    {
        id: 5,
        lenguage: "Aleman",
        company_course: "juan",
        level: "Principiante",
        instructor: "John Smith",
        schedule: "Lunes y Miércoles, 18:00 - 20:00",
        location: "Centro de Idiomas ABC",
        image: "https://www.civitatis.com/blog/wp-content/uploads/2023/03/shutterstock_1585685068-1920x1280.jpg",
        duration: "1 Month",
    },
    {
        id: 6,
        lenguage: "Chino",
        company_course: "juan",
        level: "Principiante",
        instructor: "John Smith",
        schedule: "Lunes y Miércoles, 18:00 - 20:00",
        location: "Centro de Idiomas ABC",
        image: "https://www.civitatis.com/blog/wp-content/uploads/2023/03/shutterstock_1585685068-1920x1280.jpg",
        duration: "1 Month",
    },
    {
        id: 7,
        lenguage: "Japonés",
        company_course: "juan",
        level: "Principiante",
        instructor: "John Smith",
        schedule: "Lunes y Miércoles, 18:00 - 20:00",
        location: "Centro de Idiomas ABC",
        image: "https://www.civitatis.com/blog/wp-content/uploads/2023/03/shutterstock_1585685068-1920x1280.jpg",
        duration: "1 Month",
    },
    {
        id: 8,
        lenguage: "Tailandes",
        company_course: "juan",
        level: "Principiante",
        instructor: "John Smith",
        schedule: "Lunes y Miércoles, 18:00 - 20:00",
        location: "Centro de Idiomas ABC",
        image: "https://www.civitatis.com/blog/wp-content/uploads/2023/03/shutterstock_1585685068-1920x1280.jpg",
        duration: "1 Month",
    },
    {
        id: 9,
        lenguage: "Latín",
        company_course: "juan",
        level: "Principiante",
        instructor: "John Smith",
        schedule: "Lunes y Miércoles, 18:00 - 20:00",
        location: "Centro de Idiomas ABC",
        image: "https://www.civitatis.com/blog/wp-content/uploads/2023/03/shutterstock_1585685068-1920x1280.jpg",
        duration: "1 Month",
    },
    {
        id: 10,
        lenguage: "Español",
        company_course: "juan",
        level: "Principiante",
        instructor: "John Smith",
        schedule: "Lunes y Miércoles, 18:00 - 20:00",
        location: "Centro de Idiomas ABC",
        image: "https://www.civitatis.com/blog/wp-content/uploads/2023/03/shutterstock_1585685068-1920x1280.jpg",
        duration: "1 Month",
    },
    {
        id: 11,
        lenguage: "Árabe",
        company_course: "juan",
        level: "Principiante",
        instructor: "John Smith",
        schedule: "Lunes y Miércoles, 18:00 - 20:00",
        location: "Centro de Idiomas ABC",
        image: "https://www.civitatis.com/blog/wp-content/uploads/2023/03/shutterstock_1585685068-1920x1280.jpg",
        duration: "1 Month",
    },
    {
        id: 12,
        lenguage: "Hindi",
        company_course: "juan",
        level: "Principiante",
        instructor: "John Smith",
        schedule: "Lunes y Miércoles, 18:00 - 20:00",
        location: "Centro de Idiomas ABC",
        image: "https://www.civitatis.com/blog/wp-content/uploads/2023/03/shutterstock_1585685068-1920x1280.jpg",
        duration: "1 Month",
    },
    {
        id: 13,
        lenguage: "Holandés",
        company_course: "juan",
        level: "Principiante",
        instructor: "John Smith",
        schedule: "Lunes y Miércoles, 18:00 - 20:00",
        location: "Centro de Idiomas ABC",
        image: "https://www.civitatis.com/blog/wp-content/uploads/2023/03/shutterstock_1585685068-1920x1280.jpg",
        duration: "1 Month",
    },
    {
        id: 14,
        lenguage: "Turco",
        company_course: "juan",
        level: "Principiante",
        instructor: "John Smith",
        schedule: "Lunes y Miércoles, 18:00 - 20:00",
        location: "Centro de Idiomas ABC",
        image: "https://www.civitatis.com/blog/wp-content/uploads/2023/03/shutterstock_1585685068-1920x1280.jpg",
        duration: "1 Month",
    },
    {
        id: 15,
        lenguage: "Sueco",
        company_course: "juan",
        level: "Principiante",
        instructor: "John Smith",
        schedule: "Lunes y Miércoles, 18:00 - 20:00",
        location: "Centro de Idiomas ABC",
        image: "https://www.civitatis.com/blog/wp-content/uploads/2023/03/shutterstock_1585685068-1920x1280.jpg",
        duration: "1 Month",
    },

];