[
  {
      "id": 1,
      "lenguage": "English",
      "level": "Beginner",
      "price": 100,
      "duration": "1 Month",
      "schedule": "During the week",
      "start_time": "09:00",
      "finish_time": "11:00",
      "location": "London",
      "image": "https://i.pinimg.com/474x/3a/6f/e7/3a6fe7dd295c100d9cf7e4391903bd1c.jpg"
  },
  {
      "id": 2,
      "lenguage": "English",
      "level": "Intermediate",
      "price": 150,
      "duration": "2 Months",
      "schedule": "Monday-Wednesday-Friday",
      "start_time": "14:00",
      "finish_time": "16:00",
      "location": "New York",
      "image": "https://i.pinimg.com/736x/d7/6f/a7/d76fa7daeff04830b64092e6f4e25249.jpg"
  },
  {
      "id": 3,
      "lenguage": "English",
      "level": "Advanced",
      "price": 200,
      "duration": "3 Months",
      "schedule": "Tuesday-Thursday",
      "start_time": "18:00",
      "finish_time": "20:00",
      "location": "Los Angeles",
      "image": "https://i.pinimg.com/736x/63/e4/0e/63e40e34c0102252e50c9e62221b8ffc.jpg"
  },
  {
      "id": 4,
      "lenguage": "French",
      "level": "Beginner",
      "price": 75,
      "duration": "1 Month",
      "schedule": "On Weekends",
      "start_time": "10:00",
      "finish_time": "12:00",
      "location": "Paris",
      "image": "https://eldinero.com.do/wp-content/uploads/La-ley-de-Transicion-Energetica-francesa-un-modelo-a-seguir-1.jpg"
  },
  {
      "id": 5,
      "lenguage": "French",
      "level": "Intermediate",
      "price": 125,
      "duration": "2 Months",
      "schedule": "During the week",
      "start_time": "16:00",
      "finish_time": "18:00",
      "location": "Nice",
      "image": "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/16/af/32/7d/vista-nocturna.jpg?w=1200&h=700&s=1"
  },
  {
      "id": 6,
      "lenguage": "French",
      "level": "Advanced",
      "price": 175,
      "duration": "3 Months",
      "schedule": "Monday-Wednesday-Friday",
      "start_time": "19:00",
      "finish_time": "21:00",
      "location": "Marseille",
      "image": "https://cdn.pixabay.com/photo/2018/04/25/09/26/eiffel-tower-3349075_640.jpg"
  },
  {
      "id": 7,
      "lenguage": "German",
      "level": "Beginner",
      "price": 90,
      "duration": "1 Month",
      "schedule": "During the week",
      "start_time": "11:00",
      "finish_time": "13:00",
      "location": "Berlin",
      "image": "https://images.hola.com/imagenes/viajes/20220919217396/lugares-bonitos-viajar-alemania/1-139-994/lugares-mas-bonitos-viajar-alemania-m.jpg?tx=w_680"
  },
  {
      "id": 8,
      "lenguage": "German",
      "level": "Intermediate",
      "price": 140,
      "duration": "2 Months",
      "schedule": "On Weekends",
      "start_time": "15:00",
      "finish_time": "17:00",
      "location": "Munich",
      "image": "https://images.ecestaticos.com/AY5CPt5d1hAl97xuSUUq2e2sdig=/0x0:2272x1730/1200x900/filters:fill(white):format(jpg)/f.elconfidencial.com%2Foriginal%2F867%2Fc06%2F8e4%2F867c068e48b29b5b4c3ecef6e48ffe5f.jpg"
  },
  {
      "id": 9,
      "lenguage": "German",
      "level": "Advanced",
      "price": 190,
      "duration": "3 Months",
      "schedule": "Tuesday-Thursday",
      "start_time": "20:00",
      "finish_time": "22:00",
      "location": "Hamburg",
      "image": "https://www.deutschland.de/sites/default/files/styles/pillarpage_stage_mobile/public/media/image/Brandenburger-Tor-Tatsachen-Deutschland.jpg?itok=rcg1cl-Y"
  },
  {
      "id": 10,
      "lenguage": "Italian",
      "level": "Beginner",
      "price": 80,
      "duration": "1 Month",
      "schedule": "Monday-Wednesday-Friday",
      "start_time": "12:00",
      "finish_time": "14:00",
      "location": "Rome",
      "image": "https://media.admagazine.com/photos/618a5fbfa9f7fab6f0622c3e/master/w_1600%2Cc_limit/87986.jpg"
  },
  {
      "id": 11,
      "lenguage": "Italian",
      "level": "Intermediate",
      "price": 130,
      "duration": "2 Months",
      "schedule": "During the week",
      "start_time": "17:00",
      "finish_time": "19:00",
      "location": "Florence",
      "image": "https://queverenitalia.com/wp-content/uploads/2019/03/bandera-de-italia.jpg"
  },
  {
      "id": 12,
      "lenguage": "Italian",
      "level": "Advanced",
      "price": 180,
      "duration": "3 Months",
      "schedule": "On Weekends",
      "start_time": "21:00",
      "finish_time": "23:00",
      "location": "Milan",
      "image": "https://static.wixstatic.com/media/12f2a4_08fcc88c9325403ab3f0c18aafe629b5~mv2.jpg/v1/fill/w_640,h_966,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/12f2a4_08fcc88c9325403ab3f0c18aafe629b5~mv2.jpg"
  },
  {
      "id": 13,
      "lenguage": "Dutch",
      "level": "Beginner",
      "price": 85,
      "duration": "1 Month",
      "schedule": "Tuesday-Thursday",
      "start_time": "13:00",
      "finish_time": "15:00",
      "location": "Amsterdam",
      "image": "https://fotografias.larazon.es/clipping/cmsimages01/2023/04/23/81244EA7-3DCA-424A-8F54-CEDC68EB0BF0/bandera-paises-bajos_98.jpg?crop=612,344,x0,y27&width=1900&height=1069&optimize=low&format=webply"
  },
  {
      "id": 14,
      "lenguage": "Dutch",
      "level": "Intermediate",
      "price": 135,
      "duration": "2 Months",
      "schedule": "Monday-Wednesday-Friday",
      "start_time": "18:00",
      "finish_time": "20:00",
      "location": "Rotterdam",
      "image": "https://www.rodrigofaria.com/wp-content/uploads/2023/09/curso-de-ingles-para-brasileiros-holanda.jpg"
  },
  {
      "id": 15,
      "lenguage": "Dutch",
      "level": "Advanced",
      "price": 185,
      "duration": "3 Months",
      "schedule": "During the week",
      "start_time": "22:00",
      "finish_time": "24:00",
      "location": "The Hague",
      "image": "https://i0.wp.com/www.lekkerholanda.com/wp-content/uploads/2022/10/Curso-holandes-online-STAP-Budget-scaled.jpeg?fit=768%2C1024&ssl=1"
  },
  {
      "id": 16,
      "lenguage": "Portuguese",
      "level": "Beginner",
      "price": 95,
      "duration": "1 Month",
      "schedule": "Monday-Wednesday-Friday",
      "start_time": "14:00",
      "finish_time": "16:00",
      "location": "Lisbon",
      "image": "https://media-public.canva.com/KzYno/MAEGU9KzYno/1/s.jpg"
  },
  {
      "id": 17,
      "lenguage": "Portuguese",
      "level": "Intermediate",
      "price": 145,
      "duration": "2 Months",
      "schedule": "On Weekends",
      "start_time": "19:00",
      "finish_time": "21:00",
      "location": "Porto",
      "image": "https://media-public.canva.com/KzYno/MAEGU9KzYno/1/s.jpg"
  },
  {
      "id": 18,
      "lenguage": "Portuguese",
      "level": "Advanced",
      "price": 195,
      "duration": "3 Months",
      "schedule": "Tuesday-Thursday",
      "start_time": "23:00",
      "finish_time": "01:00",
      "location": "Faro",
      "image": "https://media-public.canva.com/KzYno/MAEGU9KzYno/1/s.jpg"
  }
]
